//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BminingBlazor.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BminingBlazor.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Member.
        /// </summary>
        internal static string AddMember {
            get {
                return ResourceManager.GetString("AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Payment Status.
        /// </summary>
        internal static string AddPaymentStatus {
            get {
                return ResourceManager.GetString("AddPaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Approve.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to delete?.
        /// </summary>
        internal static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Billing Deadline.
        /// </summary>
        internal static string BillingDeadline {
            get {
                return ResourceManager.GetString("BillingDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Client.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contract Type.
        /// </summary>
        internal static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Project Manager.
        /// </summary>
        internal static string EmailProjectManager {
            get {
                return ResourceManager.GetString("EmailProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fee Contract.
        /// </summary>
        internal static string FeeContract {
            get {
                return ResourceManager.GetString("FeeContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fixed Term Contract.
        /// </summary>
        internal static string FixedTermContract {
            get {
                return ResourceManager.GetString("FixedTermContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home Address.
        /// </summary>
        internal static string HomeAddress {
            get {
                return ResourceManager.GetString("HomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indefinite Contract.
        /// </summary>
        internal static string IndefiniteContract {
            get {
                return ResourceManager.GetString("IndefiniteContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invested hours.
        /// </summary>
        internal static string InvestedHours {
            get {
                return ResourceManager.GetString("InvestedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Job.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load hours.
        /// </summary>
        internal static string LoadHours {
            get {
                return ResourceManager.GetString("LoadHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maternal Last Name.
        /// </summary>
        internal static string MaternalLastName {
            get {
                return ResourceManager.GetString("MaternalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Members.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Names.
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paternal Last Name.
        /// </summary>
        internal static string PaternalLastName {
            get {
                return ResourceManager.GetString("PaternalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Deadline Issued.
        /// </summary>
        internal static string PaymentDeadlineIssued {
            get {
                return ResourceManager.GetString("PaymentDeadlineIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project Code.
        /// </summary>
        internal static string ProjectCode {
            get {
                return ResourceManager.GetString("ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project Hours.
        /// </summary>
        internal static string ProjectHours {
            get {
                return ResourceManager.GetString("ProjectHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project Manager.
        /// </summary>
        internal static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project Name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project Status.
        /// </summary>
        internal static string ProjectStatus {
            get {
                return ResourceManager.GetString("ProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project Type.
        /// </summary>
        internal static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reasons.
        /// </summary>
        internal static string Reasons {
            get {
                return ResourceManager.GetString("Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rut.
        /// </summary>
        internal static string Rut {
            get {
                return ResourceManager.GetString("Rut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status Project.
        /// </summary>
        internal static string StatusProject {
            get {
                return ResourceManager.GetString("StatusProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
